date: 'aujourdhui'
socle_profile: 'ubuntu_server-x86_64'
liste_profils:
  - name: 'large'
    ram: '1024'
    cpu: '2'
  - name: 'medium'
    ram: '756'
    cpu: '1'
  - name: 'small'
    ram: '512'
    cpu: '1'
liste_machines:
  - name: 'web01'
    role: 'web-p'
    ip_admin: '192.168.122.210'
    ip: '172.16.0.210'
    profil: 'medium'
    disk: '20'
    hyperviseur: '192.168.122.1'
  - name: 'bdd01'
    role: 'bdd-p'
    ip_admin: '192.168.122.220'
    ip: '172.16.0.220'
    profil: 'large'
    disk: '50'
    hyperviseur: '192.168.122.10'
  - name: 'ldap01'
    role: 'ldap-p'
    ip_admin: '192.168.122.230'
    ip: '172.16.0.230'
    profil: 'small'
    disk: '20'
    hyperviseur: '192.168.122.100'
