date: 'aujourdhui'
liste_machines:
  - name: 'dummy'
    role: 'web-p'
    ip_admin: '192.168.122.200'
    ip_frontend: '172.16.0.200'
    ip_backend: '192.168.0.200'
  - name: 'dummy2'
    role: 'web-s'
    ip_admin: '192.168.122.201'
    ip_frontend: '172.16.0.201'
    ip_backend: '192.168.0.201'
  - name: 'web01'
    role: 'web-p'
    ip_admin: '192.168.122.202'
    ip_frontend: '172.16.0.202'
    ip_backend: '192.168.0.202'
