date: 'aujourdhui'
hyperviseur: '192.168.122.1'
liste_profils:
  - name: 'large'
    - ram: '1024'
      cpu: '2'
  - name: 'medium'
    - ram: '756'
      cpu: '1'
  - name: 'small'
    - ram: '512'
      cpu: '1'

liste_machines:
  - name: 'web01'
    role: 'web-p'
    ip_admin: '192.168.122.210'
    ip_frontend: '172.16.0.210'
    ip_backend: '192.168.0.210'
    profil: 'medium'
  - name: 'bdd01'
    role: 'bdd-p'
    ip_admin: '192.168.122.220'
    ip_frontend: '172.16.0.220'
    ip_backend: '192.168.0.220'
    profil: 'large'
  - name: 'ldap01'
    role: 'ldap-p'
    ip_admin: '192.168.122.230'
    ip_frontend: '172.16.0.230'
    ip_backend: '192.168.0.230'
    profil: 'small'
