date: 'aujourdhui'
liste_machines:
  - name: 'web01'
    role: 'web-p'
    ip_admin: '192.168.122.210'
    ip_frontend: '172.16.0.210'
    ip_backend: '192.168.0.210'
  - name: 'bdd01'
    role: 'bdd-p'
    ip_admin: '192.168.122.220'
    ip_frontend: '172.16.0.220'
    ip_backend: '192.168.0.220'
  - name: 'ldap01'
    role: 'ldap-p'
    ip_admin: '192.168.122.230'
    ip_frontend: '172.16.0.230'
    ip_backend: '192.168.0.230'
