date: 'aujourdhui'
socle_profile: 'ubuntu_server-x86_64'
liste_profils:
  - name: 'large'
    ram: '1024'
    cpu: '2'
  - name: 'medium'
    ram: '756'
    cpu: '1'
  - name: 'small'
    ram: '512'
    cpu: '1'
liste_machines:
  # J-C
  - name: 'web01'
    role: 'web-p'
    ip: '192.168.200.20'
    profil: 'medium'
    disk: '20'
    hyperviseur: '10.189.250.143'
    bridge: 'usb-BFAE41'

  - name: 'bdd01'
    role: 'bdd-p'
    ip: '192.168.200.30'
    profil: 'large'
    disk: '50'
    hyperviseur: '10.189.250.143'
    bridge: 'usb-BFAE41'

  - name: 'haproxy01'
    role: 'ha-p'
    ip: '192.168.200.40'
    profil: 'medium'
    disk: '20'
    hyperviseur: '10.189.250.143'
    bridge: 'usb-BFAE41'

  # Edouard
  - name: 'web02'
    role: 'web-p'
    ip: '192.168.200.21'
    profil: 'medium'
    disk: '20'
    hyperviseur: '10.189.250.106'
    bridge: 'usb-BFAE54'
  
  - name: 'bdd02'
    role: 'bdd-b'
    ip: '192.168.200.31'
    profil: 'large'
    disk: '50'
    hyperviseur: '10.189.250.106'
    bridge: 'usb-BFAE54'
  
  - name: 'haproxy02'
    role: 'ha-s'
    ip: '192.168.200.41'
    profil: 'medium'
    disk: '20'
    hyperviseur: '10.189.250.106'
    bridge: 'usb-BFAE54'

  # Quentin
  - name: 'ldap'
    role: 'ldap-p'
    ip: '192.168.200.12'
    profil: 'medium'
    disk: '20'
    hyperviseur: '192.168.122.1'
    bridge: 'usb-BFAE53'
  
  - name: 'nfs01'
    role: 'nfs-p'
    ip: '192.168.200.50'
    profil: 'medium'
    disk: '70'
    hyperviseur: '192.168.122.1'
    bridge: 'usb-BFAE53'
  
  - name: 'infra01'
    role: 'infra-p'
    ip: '192.168.200.15'
    profil: 'large'
    disk: '70'
    hyperviseur: '192.168.122.1'
    bridge: 'usb-BFAE53'

